spring:
  datasource:
    dataSource: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1

hibernate.dialect: org.hibernate.dialect.H2Dialect

identity:
  users:
    test_user:
      name: Test user
      email: test@test.pl
      groups:
        - test